#!/usr/bin/env python3
"""make_tables.py -- build the two A5 deliverable tables from the committed outputs.

Reads   ../data/cert_<p>.out   (produced by run.sh)
        ../data/hypotheses.out (produced by hypotheses.sage)
        ../data/lmfdb_iwasawa.txt
Writes  ../data/tables.md

Table (i)  the six-row hypothesis table for prop:consequence.
Table (ii) eq:match5 extended from two primes to six: height side against L-side,
           digit for digit.
Table (iii) in-house lambda_an/mu_an against Appendix B (LMFDB).
Table (iv) the certificates in the frozen Certificates.lean shape.

MISSING IS NOT DISAGREEING.  A prime with no cert_<p>.out on disk has not been
computed; it reads "not computed" everywhere and it must NEVER raise the
stop-the-line signal.  The stop-the-line signal is reserved for the two events
that actually are one: an in-house lambda/mu that DIFFERS from Appendix B, and a
computed height side that DIFFERS from the computed L-side.  A signal that fires
on a gap is a signal nobody reads.

No number in docs/A5_REPORT.md is typed by hand; they are all copied from this
file, which is generated from the raw outputs.

Usage:  python3 make_tables.py
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "data")
PRIMES = [5, 13, 17, 29, 37, 41]

MLINE = re.compile(r"MACHINE\s+(\S+)\s+v=\s*(-?\d+)\s+prec=\s*(-?\d+)\s+digits=\[([^\]]*)\]")
HYP = re.compile(r"MACHINE hyp p=(\d+) (.*)$")


def read_machine(path):
    out = {}
    if not os.path.exists(path):
        return out
    with open(path) as fh:
        for ln in fh:
            m = MLINE.search(ln)
            if m:
                out[m.group(1)] = (
                    int(m.group(2)), int(m.group(3)),
                    [int(x) for x in m.group(4).replace(" ", "").split(",") if x],
                )
    return out


def read_scalar(path, key):
    if not os.path.exists(path):
        return None
    with open(path) as fh:
        for ln in fh:
            if ln.startswith(key):
                return ln.split(":", 1)[1].strip()
    return None


hyp = {}
hp = os.path.join(DATA, "hypotheses.out")
if os.path.exists(hp):
    with open(hp) as fh:
        for ln in fh:
            m = HYP.search(ln)
            if m:
                d = dict(kv.split("=", 1) for kv in m.group(2).split())
                hyp[int(m.group(1))] = d

lmfdb = {}
lmfdb_rows = []          # every row of the table, in file order: (p, reduction, lam, mu)
lp = os.path.join(DATA, "lmfdb_iwasawa.txt")
if os.path.exists(lp):
    with open(lp) as fh:
        for ln in fh:
            if ln.startswith("#") or not ln.strip():
                continue
            f = ln.split()
            if len(f) >= 4 and f[0].isdigit():
                lmfdb[int(f[0])] = (f[2], f[3])
                lmfdb_rows.append((int(f[0]), f[1], f[2], f[3]))

cert = {}
meta = {}
for p in PRIMES:
    path = os.path.join(DATA, "cert_%d.out" % p)
    cert[p] = read_machine(path)
    meta[p] = {
        "file": "cert_%d.out" % p,
        "exists": os.path.exists(path),
        "n": read_scalar(path, "n (approx order)"),
        "summands": (read_scalar(path, "summands in the Riemann sum") or "").split("=")[-1].strip() or None,
        "runtime": read_scalar(path, "series runtime"),
        "c2prec": read_scalar(path, "c_2 precision"),
        "c0prec": read_scalar(path, "c_0 precision"),
        "c1prec": read_scalar(path, "c_1 precision"),
        "cbound": read_scalar(path, "_c_bound()"),
        "bounds": read_scalar(path, "_prec_bounds(n,precT)"),
        "date": read_scalar(path, "date            "),
        "result": read_scalar(path, "RESULT          "),
        "Lp": read_scalar(path, "L_p(E,T)"),
        "impl": read_scalar(path, "implementation    "),
    }

lines = []
A = lines.append
A("<!-- GENERATED by series/code/lpadic/make_tables.py -- do not edit by hand. -->")
A("")
A("# A5 tables")
A("")
A("Curve `E : y^2 = x^3 - 56x`, `[0,0,0,-56,0]`, `N = 12544 = 2^8*7^2`, CM by `Z[i]`,")
A("rank 2, `#tors = 2`, `prod c_v = 4`, `d_K = -4`.")
A("Sources: `code/data/cert_<p>.out`, `code/data/hypotheses.out`,")
A("`code/data/lmfdb_iwasawa.txt`.")
A("")

# ---------------- Table (i) ----------------
A("## 2. Table (i) — the six hypotheses of `prop:consequence` at six primes")
A("")
A("Hypotheses, in the order of the `cor:sha5` proof (`main.tex`:1594–1613) and of")
A("the excluded set `eq:Sexc` (`main.tex`:1049):")
A("")
A("* **(H1)** `p` splits in `K = Q(i)`  (⟺ `p ≡ 1 (mod 4)`; also gives good ordinary reduction)")
A("* **(H2)** `p ∤ 6N·∏c_v·#tors·d_K`")
A("* **(H3)** `p` non-anomalous, i.e. `p ∤ #Ẽ(F_p) = p+1-a_p`")
A("* **(H4)** `ρ̄_{E,p}` irreducible")
A("* **(H5)** the comparison constant of `lem:comparison` is a `p`-adic unit")
A("* **(H6)** the certificate `v_p(c_2(p)) = 0`  ← the only computed hypothesis")
A("")
A("| p | H1 split, `p mod 4` | H2 `gcd(p, 6N·∏c_v·#tors·abs(d_K))` | H3 `a_p`, `#Ẽ(F_p)`, non-anom | H4 `ρ̄` irred | H5 comparison | H6 `v_p(c_2(p)) = 0` | source |")
A("|---|---|---|---|---|---|---|---|")
for p in PRIMES:
    h = hyp.get(p, {})
    c = cert.get(p, {})
    c2 = c.get("c2.modsym")
    h6 = "—"
    if c2:
        h6 = "**yes**, `v=%d`, %d digits `O(%d^%d)`" % (c2[0], len(c2[2]), p, c2[1])
    A("| **%d** | yes, %s | %s | `%s`, `%s`, %s | %s | unit (`{2,7}`) | %s | `%s` |"
      % (p,
         "1" if h.get("split") == "True" else "?",
         h.get("gcd_p_M", "?"),
         h.get("ap", "?"), h.get("NEFp", "?"),
         "yes" if h.get("nonanomalous") == "True" else "?",
         "yes" if h.get("irreducible") == "True" else "?",
         h6,
         meta[p]["file"]))
A("")
A("H1–H4 are machine-checked in `code/data/hypotheses.out` and independently re-")
A("printed in each `cert_<p>.out`. H5 is not a computation: it is quoted from the")
A("frozen `main.tex` (remark at 1037–1046, `lem:comparison` at 985), which puts the")
A("period ratio on `{2,7}`, so `v_p(c_p) = 0` at every split `p`. H6 is this track's")
A("work.")
A("")

# ---------------- Table (ii) ----------------
A("## 3. Table (ii) — `eq:match5` extended from two primes to six")
A("")
A("`eq:padicbsd` at a split prime, with `∏c_v/(#tors)^2 = 1`:")
A("")
A("        c_2(p)  =  (1 - alpha_p^{-1})^2 · Reg_p / log_p(1+p)^2 · #Sha(E/Q)[p^inf]")
A("")
A("Height side computed with `#Sha = 1`; L-side computed from modular symbols at")
A("level 12544. Digits are base-`p`, coefficient of `p^0` first.")
A("")
A("| p | n | summands | runtime | height side (Sha-factor 1) | L-side (modular symbols) | digits agreeing | `v_p(c_2)` |")
A("|---|---|---|---|---|---|---|---|")
missing = []          # primes with no certificate on disk -- a gap, NOT a disagreement
mismatch = []         # primes where a COMPUTED height side disagrees with the L-side
for p in PRIMES:
    c = cert.get(p, {})
    c2 = c.get("c2.modsym")
    hs = c.get("hs.pari")
    if not c2 or not hs:
        missing.append(p)
        A("| **%d** | — | — | — | — | — | *not computed* | — |" % p)
        continue
    k = len(c2[2])
    agree = hs[0] == c2[0] and hs[2][:k] == c2[2][:k]
    if not agree:
        mismatch.append(p)
    A("| **%d** | %s | %s | %s | `%s` | `%s + O(%d^%d)` | %s | %d |"
      % (p, meta[p]["n"], meta[p]["summands"], meta[p]["runtime"],
         hs[2][:k], c2[2], p, c2[1],
         ("**all %d**" % k) if agree else "**MISMATCH**", c2[0]))
A("")
A("Full-precision height sides (they carry more digits than the L-side certifies):")
A("")
A("| p | height side digits | `Reg_p` digits (from `p^2`) | `a_p` |")
A("|---|---|---|---|")
for p in PRIMES:
    c = cert.get(p, {})
    hs = c.get("hs.pari")
    rg = c.get("reg.pari")
    ap = c.get("ap.pari")
    if not hs:
        A("| **%d** | — | — | — |" % p)
        continue
    A("| **%d** | `%s + O(%d^%d)` | `%s + O(%d^%d)` | `%s` |"
      % (p, hs[2], p, hs[1], rg[2], p, rg[1], ap[2][0]))
A("")

# ---------------- Table (iii): LMFDB corroboration ----------------
A("## 4. Table (iii) — in-house vs Appendix B (the stop-the-line check): corroboration only")
A("")
A("A prime with no in-house certificate is a **gap**, not a disagreement: it reads")
A("*not computed* and it does not raise the stop-the-line signal. Only a computed")
A("value that differs from Appendix B does that.")
A("")
A("| p | in-house `λ_an` | in-house `μ_an` | LMFDB `λ` | LMFDB `μ` | agree? |")
A("|---|---|---|---|---|---|")
lmfdb_agree = []      # computed in-house AND agreeing with Appendix B
lmfdb_disagree = []   # computed in-house AND differing from Appendix B  <- stop the line
lmfdb_missing = []    # not computed in-house                            <- a gap
for p in PRIMES:
    c = cert.get(p, {})
    lam = c.get("lambda_an")
    mu = c.get("mu_an")
    li, mi = lmfdb.get(p, ("?", "?"))
    if not lam or not mu:
        lmfdb_missing.append(p)
        A("| **%d** | — | — | %s | %s | *not computed* |" % (p, li, mi))
        continue
    lam_s, mu_s = str(lam[2][0]), str(mu[2][0])
    ok = (lam_s == li and mu_s == mi)
    (lmfdb_agree if ok else lmfdb_disagree).append(p)
    A("| **%d** | %s | %s | %s | %s | %s |"
      % (p, lam_s, mu_s, li, mi, "yes" if ok else "**NO — STOP THE LINE**"))
A("")

# Overall verdict.  Three outcomes, deliberately distinguished:
#   (a) a computed value differs from Appendix B  -> stop the line;
#   (b) no disagreement, but some prime uncomputed -> agreement so far, plus a gap;
#   (c) every prime computed and agreeing        -> clean.
def _plist(ps):
    return ", ".join("p = %d" % q for q in ps)

if lmfdb_disagree:
    A("Overall: ***** DISAGREEMENT WITH APPENDIX B AT %s -- STOP THE LINE *****"
      % _plist(lmfdb_disagree))
    A("")
    A("This is a stop-the-line event: an in-house computation differs from LMFDB.")
elif lmfdb_missing:
    A("Overall: **no disagreement with Appendix B** — every prime computed in-house")
    A("(%s) agrees. **Not computed: %s** — a gap in coverage,"
      % (_plist(lmfdb_agree), _plist(lmfdb_missing)))
    A("not a disagreement, and not a stop-the-line event.")
else:
    A("Overall: **every prime agrees with Appendix B** (%s); none uncomputed."
      % _plist(lmfdb_agree))
A("")

# The eq:match5 comparison has its own stop-the-line condition, on computed rows only.
if mismatch:
    A("Height side vs L-side: ***** MISMATCH AT %s -- STOP THE LINE *****"
      % _plist(mismatch))
else:
    A("Height side vs L-side: **no mismatch at any computed prime**%s."
      % (" (not computed: %s)" % _plist(missing) if missing else ""))
A("")

# ---------------- Lean certificate shape (for Track C2(a)) ----------------
A("## 5. Table (iv) — the certificates in the frozen `Certificates.lean` shape")
A("")
A("The frozen tree records a digit certificate as")
A("")
A("        c2_5 : PadicInt.toZModPow 7 (PowerSeries.coeff 2 (... ).analytic.Lp)")
A("             = ((1 + 4 * 5 + 3 * 5 ^ 2 + 5 ^ 3 + 5 ^ 5 + 5 ^ 6 : ℤ) : ZMod (5 ^ 7))")
A("")
A("(`formal/FinShaRank2/Interface/Certificates.lean`). The six certificates below are")
A("emitted in that shape so that Track C2(a) can drop them in unchanged. `k` is the")
A("truncation bound actually achieved, i.e. `toZModPow k` is exactly as far as the")
A("computation certifies — no digit is invented.")
A("")
for p in PRIMES:
    c = cert.get(p, {})
    c2 = c.get("c2.modsym")
    if not c2:
        A("* `p = %d`: *not computed* — no certificate on disk (a gap, not a disagreement)." % p)
        continue
    v, k, d = c2
    terms = []
    for j, dj in enumerate(d):
        e = v + j
        if dj == 0:
            continue
        if e == 0:
            terms.append("%d" % dj)
        elif e == 1:
            terms.append(("%d * %d" % (dj, p)) if dj != 1 else "%d" % p)
        else:
            terms.append(("%d * %d ^ %d" % (dj, p, e)) if dj != 1 else "%d ^ %d" % (p, e))
    expr = " + ".join(terms) if terms else "0"
    A("* `p = %d`, `k = %d`:" % (p, k))
    A("  ```lean")
    A("  c2_%d : PadicInt.toZModPow %d (PowerSeries.coeff 2 Lp%d)" % (p, k, p))
    A("      = ((%s : ℤ) : ZMod (%d ^ %d))" % (expr, p, k))
    A("  ```")
A("")
A("Companion `a_p` certificates (`Certificates.a5`, `Certificates.a13` in the frozen")
A("tree), from `code/data/hypotheses.out`:")
A("")
for p in PRIMES:
    h = hyp.get(p, {})
    if h:
        A("* `a%d : ... .analytic.ap = %s`   (`#Ẽ(F_%d) = %s`, prime to %d)"
          % (p, h.get("ap", "?"), p, h.get("NEFp", "?"), p))
A("")

# ---------------- provenance ----------------
A("## 6. Provenance of each row")
A("")
A("| p | file | date (UTC) | approx. order `n` | `_c_bound()` | `_prec_bounds` | `c_0` | `c_1` | `c_2` | step-4 verdict |")
A("|---|---|---|---|---|---|---|---|---|---|")
for p in PRIMES:
    m = meta[p]
    A("| **%d** | `%s` | %s | %s | %s | `%s` | %s | %s | %s | %s |"
      % (p, m["file"], m["date"] or "—", m["n"] or "—", m["cbound"] or "—",
         m["bounds"] or "—",
         (m["c0prec"] or "—").split()[0], (m["c1prec"] or "—").split()[0],
         (m["c2prec"] or "—").split()[0], m["result"] or "—"))
A("")
A("Computed `L_p(E,T)` as returned by Sage:")
A("")
for p in PRIMES:
    if meta[p]["Lp"]:
        A("* `p = %d`: `%s`" % (p, meta[p]["Lp"]))
A("")

out = os.path.join(DATA, "tables.md")
with open(out, "w") as fh:
    fh.write("\n".join(lines) + "\n")
print("wrote %s" % os.path.abspath(out))

# ==================================================================
#  LaTeX emitter -- the same numbers, in the shape the Paper I
#  fragments use.  The fragments must be SELF-CONTAINED (they cannot
#  \input this file), so the blocks below are pasted into
#  paper1-sha/fragments/*.tex between BEGIN/END GENERATED markers.
#  Re-run this script and re-paste after any precision upgrade; that
#  is the only hand step, and it copies, it does not retype.
# ==================================================================

def padic_tex(v, digits, p, k):
    r"""base-p expansion as LaTeX, e.g. 1 + 4\cdot 5 + 3\cdot 5^2 + O(5^7)."""
    terms = []
    for j, dj in enumerate(digits):
        e = v + j
        if dj == 0:
            continue
        if e == 0:
            terms.append("%d" % dj)
        elif e == 1:
            terms.append(("%d\\cdot %d" % (dj, p)) if dj != 1 else "%d" % p)
        else:
            terms.append(("%d\\cdot %d^{%d}" % (dj, p, e)) if dj != 1
                         else "%d^{%d}" % (p, e))
    body = " + ".join(terms) if terms else "0"
    return "%s + O(%d^{%d})" % (body, p, k)


tex = []
B = tex.append
B("%% GENERATED by series/code/lpadic/make_tables.py from code/data/cert_<p>.out")
B("%% and code/data/hypotheses.out.  Do not edit by hand: re-run and re-paste.")
B("")

# ---- (1) the certificates ----
B("%% ---------------- BEGIN GENERATED certificates-table ----------------")
B("\\begin{tabular}{cccccl}")
B("\\hline")
B("$p$ & $a_p$ & $n$ & summands & $v_p(c_2(p))$ & $c_2(p)$ \\\\")
B("\\hline")
for p_ in PRIMES:
    c = cert.get(p_, {})
    c2 = c.get("c2.modsym")
    h = hyp.get(p_, {})
    if not c2:
        B("$%d$ & $%s$ & --- & --- & \\multicolumn{2}{l}{\\emph{not computed}} \\\\"
          % (p_, h.get("ap", "?")))
        continue
    v, k, d = c2
    B("$%d$ & $%s$ & $%s$ & $%s$ & $%d$ & $%s$ \\\\"
      % (p_, h.get("ap", "?"), meta[p_]["n"], meta[p_]["summands"], v,
         padic_tex(v, d, p_, k)))
B("\\hline")
B("\\end{tabular}")
B("%% ---------------- END GENERATED certificates-table ------------------")
B("")

# ---- (2) the eq:padicbsd match, height side against L-side ----
# Two rows per prime: the columns are narrow enough to fit the text block,
# and the layout mirrors the way eq:match5 is displayed in the source paper.
B("%% ---------------- BEGIN GENERATED match-table -----------------------")
B("\\begin{tabular}{clc}")
B("\\hline")
B("$p$ & the two sides of \\eqref{eq:padicbsd} & digits agreeing \\\\")
B("\\hline")
for i, p_ in enumerate(PRIMES):
    c = cert.get(p_, {})
    c2, hs = c.get("c2.modsym"), c.get("hs.pari")
    gap = "" if i == len(PRIMES) - 1 else "[2pt]"
    if not c2 or not hs:
        B("$%d$ & \\emph{not computed} & --- \\\\%s" % (p_, gap))
        continue
    k = len(c2[2])
    ok = hs[0] == c2[0] and hs[2][:k] == c2[2][:k]
    B("$%d$ & height side\\quad $%s$ & \\\\"
      % (p_, padic_tex(hs[0], hs[2][:k], p_, c2[1])))
    B("    & $L$-side\\quad\\ \\ $%s$ & %s \\\\%s"
      % (padic_tex(c2[0], c2[2], p_, c2[1]),
         ("all $%d$" % k) if ok else "\\textbf{MISMATCH}", gap))
B("\\hline")
B("\\end{tabular}")
B("%% ---------------- END GENERATED match-table -------------------------")
B("")

# ---- (3) the hypotheses H1-H6 ----
B("%% ---------------- BEGIN GENERATED hypotheses-table ------------------")
B("\\begin{tabular}{ccccccl}")
B("\\hline")
B("$p$ & (H1) & (H2) & (H3) & (H4) & (H5) & (H6) $v_p(c_2(p)) = 0$ \\\\")
B(" & split & $\\gcd(p,M)$ & $a_p$, $\\#\\widetilde E(\\F_p)$ & $\\bar\\rho$ irr."
  " & comparison & \\\\")
B("\\hline")
for p_ in PRIMES:
    h = hyp.get(p_, {})
    c2 = cert.get(p_, {}).get("c2.modsym")
    h6 = ("certified, $O(%d^{%d})$" % (p_, c2[1])) if c2 else "\\emph{not computed}"
    B("$%d$ & %s & $%s$ & $%s$, $%s$ & %s & unit & %s \\\\"
      % (p_,
         "yes" if h.get("split") == "True" else "?",
         h.get("gcd_p_M", "?"), h.get("ap", "?"), h.get("NEFp", "?"),
         "yes" if h.get("irreducible") == "True" else "?", h6))
B("\\hline")
B("\\end{tabular}")
B("%% ---------------- END GENERATED hypotheses-table --------------------")
B("")

# ---- (4) in-house against LMFDB ----
B("%% ---------------- BEGIN GENERATED lmfdb-table -----------------------")
B("\\begin{tabular}{ccccccc}")
B("\\hline")
B("$p$ & in-house $\\lambda_{\\mathrm{an}}$ & in-house $\\mu_{\\mathrm{an}}$"
  " & precision & LMFDB $\\lambda$ & LMFDB $\\mu$ & agree \\\\")
B("\\hline")
for p_ in PRIMES:
    c = cert.get(p_, {})
    lam, mu, c2 = c.get("lambda_an"), c.get("mu_an"), c.get("c2.modsym")
    li, mi = lmfdb.get(p_, ("?", "?"))
    if not lam or not mu:
        B("$%d$ & --- & --- & --- & $%s$ & $%s$ & \\emph{not computed} \\\\"
          % (p_, li, mi))
        continue
    ls, ms = str(lam[2][0]), str(mu[2][0])
    B("$%d$ & $%s$ & $%s$ & $O(%d^{%d})$ & $%s$ & $%s$ & %s \\\\"
      % (p_, ls, ms, p_, c2[1], li, mi,
         "yes" if (ls == li and ms == mi) else "\\textbf{NO --- STOP THE LINE}"))
B("\\hline")
B("\\end{tabular}")
B("%% ---------------- END GENERATED lmfdb-table -------------------------")
B("")

# ---- (5) the p-adic regulators, truncated for display ----
NDISP = 6
B("%% ---------------- BEGIN GENERATED regulator-table -------------------")
B("\\begin{tabular}{ccl}")
B("\\hline")
B("$p$ & $v_p(\\Reg_p)$ & $\\Reg_p$ \\\\")
B("\\hline")
for p_ in PRIMES:
    c = cert.get(p_, {})
    rg = c.get("reg.pari")
    if not rg:
        B("$%d$ & --- & \\emph{not computed} \\\\" % p_)
        continue
    v, k, d = rg
    B("$%d$ & $%d$ & $%s$ \\\\"
      % (p_, v, padic_tex(v, d[:NDISP], p_, v + NDISP)))
B("\\hline")
B("\\end{tabular}")
B("%% ---------------- END GENERATED regulator-table ---------------------")
B("")

# ---- (6) the published table itself, all primes, verbatim ----
REDUCTION = {"add": "additive", "ord": "ordinary", "ss": "supersingular"}
B("%% ---------------- BEGIN GENERATED lmfdb-full-table ------------------")
B("\\begin{tabular}{cccc}")
B("\\hline")
B("$p$ & reduction & $\\lambda$ & $\\mu$ \\\\")
B("\\hline")
for (p_, red, lam, mu) in lmfdb_rows:
    used = (red == "ord")
    fmt = (lambda x: "\\mathbf{%s}" % x.replace(",", ",\\,")) if used \
        else (lambda x: x.replace(",", ",\\,"))
    name = REDUCTION.get(red, red)
    if used:
        name = "\\textbf{%s}" % name
    B("$%s$ & %s & $%s$ & $%s$ \\\\"
      % (("\\mathbf{%d}" % p_) if used else str(p_), name,
         fmt(lam) if lam != "-" else "\\text{---}",
         fmt(mu) if mu != "-" else "\\text{---}"))
B("\\hline")
B("\\end{tabular}")
B("%% ---------------- END GENERATED lmfdb-full-table --------------------")
B("")

outtex = os.path.join(DATA, "tables.tex")
with open(outtex, "w") as fh:
    fh.write("\n".join(tex) + "\n")
print("wrote %s" % os.path.abspath(outtex))

if "--quiet" not in sys.argv:
    print("\n".join(lines))
