#!/usr/bin/env python3
r"""paste_tables.py -- copy the generated LaTeX tables into the Paper I fragments.

The fragments under paper1-sha/fragments/ must be SELF-CONTAINED (the PM splices
them, and they cannot \input a generated file), so the tables generated by
make_tables.py into code/data/tables.tex are *pasted* into them, between

    %% ---------------- BEGIN GENERATED <name>-table ...
    ...
    %% ---------------- END GENERATED <name>-table ...

markers.  This script does the pasting, so that after a precision upgrade the whole
drill is

    python3 make_tables.py --quiet && python3 paste_tables.py

and no digit is ever retyped.  Idempotent; prints what it changed.  Any provenance
or PRECISION-DEPENDENT comment belongs OUTSIDE the markers, above the BEGIN line:
everything between the markers is overwritten.

Usage:  python3 paste_tables.py [--check]
        --check exits 2 if any fragment is out of date, and writes nothing.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
TABLES = os.path.join(ROOT, "code", "data", "tables.tex")
FRAGS = os.path.join(ROOT, "paper1-sha", "fragments")

BEGIN = re.compile(r"^%%\s*-+\s*BEGIN GENERATED (\S+?)-table\s*-*\s*$")
END = re.compile(r"^%%\s*-+\s*END GENERATED (\S+?)-table\s*-*\s*$")

check = "--check" in sys.argv

# ---- read the generated blocks ----
blocks, name, buf = {}, None, []
for ln in open(TABLES).read().splitlines():
    m = BEGIN.match(ln)
    if m:
        name, buf = m.group(1), []
        continue
    m = END.match(ln)
    if m:
        if name != m.group(1):
            sys.exit("tables.tex: BEGIN %r closed by END %r" % (name, m.group(1)))
        blocks[name] = buf
        name = None
        continue
    if name is not None:
        buf.append(ln)
if name is not None:
    sys.exit("tables.tex: unterminated block %r" % name)
if not blocks:
    sys.exit("tables.tex: no BEGIN/END GENERATED blocks found")

# ---- paste into every fragment that asks for one ----
stale, changed = [], []
for fn in sorted(os.listdir(FRAGS)):
    if not fn.endswith(".tex"):
        continue
    path = os.path.join(FRAGS, fn)
    src = open(path).read().splitlines()
    out, i, touched = [], 0, []
    while i < len(src):
        m = BEGIN.match(src[i])
        if not m:
            out.append(src[i])
            i += 1
            continue
        nm = m.group(1)
        if nm not in blocks:
            sys.exit("%s wants block %r, which tables.tex does not define" % (fn, nm))
        j = i + 1
        while j < len(src) and not END.match(src[j]):
            j += 1
        if j >= len(src):
            sys.exit("%s: unterminated block %r" % (fn, nm))
        if src[i + 1:j] != blocks[nm]:
            touched.append(nm)
        out.append(src[i])
        out.extend(blocks[nm])
        out.append(src[j])
        i = j + 1
    if touched:
        if check:
            stale.append("%s: %s" % (fn, ", ".join(touched)))
        else:
            open(path, "w").write("\n".join(out) + "\n")
            changed.append("%s: %s" % (fn, ", ".join(touched)))

if check:
    if stale:
        print("OUT OF DATE:")
        for s in stale:
            print("  " + s)
        sys.exit(2)
    print("all generated tables in the fragments are up to date")
else:
    for c in changed:
        print("updated  " + c)
    if not changed:
        print("no change: fragments already match code/data/tables.tex")
