#!/bin/bash
# reach.sh -- R4 reach-and-cost runner for E : y^2 = x^3 - 56x.
#
#   ./reach.sh <pmin> <pmax> [precT] [cap_per_prime_s] [budget_s] [nmax]
#
# Produces  ../data/reach_<pmin>_<pmax>.out  containing, verbatim:
#   0. a header: date, host, exact command, software versions -- the same header
#      run.sh writes on a certificate, so the file is auditable the same way;
#   1. reach.sage -- for each split prime p in [pmin, pmax], v_p(c_2(p)) at the
#      MINIMAL approximation order n that certifies it, the number of summands
#      (p-1)*p^(n-1), the certified modulus p^(n-1), and the wall-clock time;
#      with the one-off cost of the space of modular symbols at level 12544
#      timed and reported SEPARATELY from the per-prime cost.
#
# THIS IS NOT run.sh.  run.sh produces a certificate: two independent Reg_p
# implementations, the Gram-determinant saturation check, the eq:match5
# comparison, and check_agreement.py's C1-C7.  reach.sh runs one implementation
# at minimal precision and performs none of those cross-checks.  Its output
# measures where the input of prop:criterion remains available and what it costs.
# It supports no theorem.  See ss:standards.
#
# CAPS.  `timeout` is not on the local macOS PATH; caps are enforced inside Sage
# by alarm(), as in certificates.sage.  A prime that hits its cap is recorded
# with the stage it reached and the scan stops; the global budget stops the scan
# cleanly between primes.  Unfinished runs are reported, never dropped.

set -u

PMIN="${1:?usage: reach.sh <pmin> <pmax> [precT] [cap_per_prime_s] [budget_s] [nmax]}"
PMAX="${2:?usage: reach.sh <pmin> <pmax> [precT] [cap_per_prime_s] [budget_s] [nmax]}"
PRECT="${3:-5}"
CAP="${4:-0}"
BUDGET="${5:-0}"
NMAX="${6:-3}"

HERE="$(cd "$(dirname "$0")" && pwd)"
DATA="$HERE/../data"
SAGE="${SAGE:-/usr/local/bin/sage}"

mkdir -p "$DATA"
WORK="$(mktemp -d "${TMPDIR:-/tmp}/reach_${PMIN}_${PMAX}_XXXXXX")"
cp "$HERE/reach.sage" "$WORK/"
OUT="$DATA/reach_${PMIN}_${PMAX}.out"
TMPOUT="$WORK/reach_${PMIN}_${PMAX}.out"

{
  echo "==============================================================================="
  echo "R4 REACH MEASUREMENT -- split primes $PMIN .. $PMAX"
  echo "E : y^2 = x^3 - 56x   [0,0,0,-56,0]   conductor 12544 = 2^8 * 7^2"
  echo "==============================================================================="
  echo "date            : $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
  echo "host            : $(hostname)  $(uname -srm)"
  echo "sage            : $SAGE  --  $($SAGE --version 2>&1 | head -1)"
  echo "python3         : $(python3 --version 2>&1)"
  echo "generated by    : series/code/lpadic/reach.sh $PMIN $PMAX $PRECT $CAP $BUDGET $NMAX"
  echo "commands run    : (script is series/code/lpadic/reach.sage, copied to a scratch dir)"
  echo "    sage reach.sage $PMIN $PMAX $PRECT $CAP $BUDGET $NMAX"
  echo "status          : COST AND REACH MEASUREMENT -- NOT A CERTIFICATE."
  echo "                  One implementation, minimal precision, no Reg_p"
  echo "                  cross-check, no eq:match5 comparison, no"
  echo "                  check_agreement.py.  Supports no theorem."
  echo "-------------------------------------------------------------------------------"
  echo
  ( cd "$WORK" && "$SAGE" reach.sage "$PMIN" "$PMAX" "$PRECT" "$CAP" "$BUDGET" "$NMAX" 2>&1 )
  echo "exit status     : $?"
  echo
  echo "=== END reach $PMIN .. $PMAX ==="
} > "$TMPOUT" 2>&1

mv "$TMPOUT" "$OUT"
echo "wrote -> $OUT"
grep -E "^SUMMARY|^largest split prime|^stop reason|CAP HIT|BUDGET EXPIRED" "$OUT" | tail -10
rm -rf "$WORK"
