#!/bin/bash
# run.sh -- A5 certificate runner for E : y^2 = x^3 - 56x at a split ordinary p.
#
#   ./run.sh <p> <n> [precT] [cap_seconds]
#
# Produces  ../data/cert_<p>.out  containing, verbatim and in this order:
#   0. a header: date, host, exact commands, software versions;
#   1. regulator.gp      -- Reg_p and the height side by PARI/GP  (implementation 1)
#   2. regulator.sage    -- Reg_p and the height side by Sage     (implementation 2)
#   3. certificates.sage -- L_p(E,T) by modular symbols at level 12544, the
#                           Stein-Wuthrich truncation bound achieved, v_p(c_2(p)),
#                           the digits of c_2(p), lambda_an / mu_an, and the
#                           eq:match5 digit-for-digit comparison;
#   4. check_agreement.py-- mechanical cross-checks C1-C7 over the MACHINE lines
#                           emitted by steps 1-3: the two Reg_p implementations,
#                           the Gram-determinant saturation check, the eq:match5
#                           match, the certificate v_p(c_2(p)) = 0, and the
#                           corroboration check against Appendix B (LMFDB).
#
# ATOMICITY.  Everything runs in a private scratch directory (a copy of the three
# scripts, so that concurrent runs at different primes cannot race on Sage's
# `<script>.sage.py` preparse artefact), and the result is moved into
# ../data/ only at the end:
#     step 4 fails            -> ../data/cert_<p>.FAILED.out
#     step 4 passes, more or
#       equal certified digits -> ../data/cert_<p>.out   (replaces)
#     step 4 passes, but FEWER
#       certified digits       -> ../data/cert_<p>.superseded.out
# In the last two cases an existing good ../data/cert_<p>.out is kept unless the new
# run is at least as precise, so neither a long ambitious run that hits its cap NOR a
# cheap low-n re-run can take away digits that have already been earned.  Precision is
# compared on the k in "c_2 precision : O(p^k)", the truncation bound actually
# achieved.  Consequence: the runner is safe to re-run at any n, in any order, any
# number of times.
#
# CAPS.  `timeout` is not on the local macOS PATH, so the cap is enforced inside
# Sage by alarm(): certificates.sage takes cap_seconds as its fourth argument and
# prints "CAP HIT" and exits 2 rather than running away.  The PARI and Sage
# regulator steps are seconds and are not capped.
#
# COST.  certificates.sage sums (p-1)*p^(n-1) modular symbols and certifies
# c_2(p) modulo p^(n-1).  Each extra certified digit multiplies the cost by p;
# n = 2 already suffices for v_p(c_2(p)) = 0.

set -u

P="${1:?usage: run.sh <p> <n> [precT] [cap_seconds]}"
N="${2:?usage: run.sh <p> <n> [precT] [cap_seconds]}"
PRECT="${3:-5}"
CAP="${4:-0}"

HERE="$(cd "$(dirname "$0")" && pwd)"
DATA="$HERE/../data"
SAGE="${SAGE:-/usr/local/bin/sage}"
GP="${GP:-/opt/homebrew/bin/gp}"

mkdir -p "$DATA"
WORK="$(mktemp -d "${TMPDIR:-/tmp}/a5_p${P}_XXXXXX")"
cp "$HERE/regulator.gp" "$HERE/regulator.sage" "$HERE/certificates.sage" \
   "$HERE/check_agreement.py" "$WORK/"
TMPOUT="$WORK/cert_${P}.out"

{
  echo "==============================================================================="
  echo "A5 CERTIFICATE -- p = $P"
  echo "E : y^2 = x^3 - 56x   [0,0,0,-56,0]   conductor 12544 = 2^8 * 7^2"
  echo "==============================================================================="
  echo "date            : $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
  echo "host            : $(hostname)  $(uname -srm)"
  echo "sage            : $SAGE  --  $($SAGE --version 2>&1 | head -1)"
  echo "gp              : $GP  --  PARI/GP $(echo 'print(version())' | $GP -q 2>/dev/null | tail -1)"
  echo "python3         : $(python3 --version 2>&1)"
  echo "generated by    : series/code/lpadic/run.sh $P $N $PRECT $CAP"
  echo "commands run    : (scripts are series/code/lpadic/*, copied to a scratch dir)"
  echo "    P=$P NPREC=14 gp -q regulator.gp"
  echo "    sage regulator.sage $P 14"
  echo "    sage certificates.sage $P $N $PRECT $CAP"
  echo "    python3 check_agreement.py $P cert_${P}.out ../data/lmfdb_iwasawa.txt"
  echo "-------------------------------------------------------------------------------"
  echo
  echo "=== STEP 1/4 : Reg_p, implementation 1 of 2 -- PARI/GP ellpadicregulator ==="
  ( cd "$WORK" && P="$P" NPREC=14 "$GP" -q regulator.gp 2>&1 ); echo "exit status     : $?"
  echo
  echo "=== STEP 2/4 : Reg_p, implementation 2 of 2 -- Sage padic_regulator ==="
  ( cd "$WORK" && "$SAGE" regulator.sage "$P" 14 2>&1 ); echo "exit status     : $?"
  echo
  echo "=== STEP 3/4 : L-side, modular symbols at level 12544 (Stein-Wuthrich) ==="
  ( cd "$WORK" && "$SAGE" certificates.sage "$P" "$N" "$PRECT" "$CAP" 2>&1 ); echo "exit status     : $?"
  echo
} > "$TMPOUT" 2>&1

# Step 4 reads the file written so far and appends its verdict to it.
{
  echo "=== STEP 4/4 : mechanical cross-checks (check_agreement.py) ==="
  python3 "$WORK/check_agreement.py" "$P" "$TMPOUT" "$DATA/lmfdb_iwasawa.txt" 2>&1
  RC=$?
  echo "exit status     : $RC"
  echo
  echo "=== END p = $P ==="
} >> "$TMPOUT" 2>&1

# Number of certified base-p digits of c_2, i.e. the k in "c_2 precision : O(p^k)".
# Empty if absent.
digits_of() {
  [ -f "$1" ] || { echo ""; return; }
  sed -n 's/^c_2 precision *: O(p^\([0-9][0-9]*\)).*/\1/p' "$1" | head -1
}

CERT="$DATA/cert_${P}.out"
NEWK="$(digits_of "$TMPOUT")"
OLDK="$(digits_of "$CERT")"

if ! grep -q "^RESULT            : ALL CHECKS PASS" "$TMPOUT"; then
  mv "$TMPOUT" "$DATA/cert_${P}.FAILED.out"
  echo "FAIL       -> $DATA/cert_${P}.FAILED.out   (existing cert_${P}.out untouched)"
elif [ -z "$NEWK" ]; then
  # Checks passed but the precision line is unreadable: refuse to touch a good file.
  mv "$TMPOUT" "$DATA/cert_${P}.FAILED.out"
  echo "FAIL       -> $DATA/cert_${P}.FAILED.out   (checks passed but c_2 precision unparseable;"
  echo "              existing cert_${P}.out untouched)"
elif [ -z "$OLDK" ]; then
  mv "$TMPOUT" "$CERT"
  echo "PASS  new  -> $CERT   (O(${P}^${NEWK}), no previous certificate)"
elif [ "$NEWK" -gt "$OLDK" ]; then
  mv "$TMPOUT" "$CERT"
  echo "PASS  up   -> $CERT   (O(${P}^${OLDK}) -> O(${P}^${NEWK}))"
elif [ "$NEWK" -eq "$OLDK" ]; then
  mv "$TMPOUT" "$CERT"
  echo "PASS  same -> $CERT   (O(${P}^${NEWK}), reproduced at the same precision)"
else
  # A LOWER-PRECISION run must never replace a higher-precision certificate, even
  # though all its checks passed: that would silently give away certified digits.
  mv "$TMPOUT" "$DATA/cert_${P}.superseded.out"
  echo "PASS  low  -> $DATA/cert_${P}.superseded.out"
  echo "              O(${P}^${NEWK}) does not beat the O(${P}^${OLDK}) already in"
  echo "              $CERT, which is KEPT.  Nothing was lost; re-run with a larger n."
fi
grep -E "^RESULT|STOP THE LINE|CAP HIT" "$DATA/cert_${P}"*.out 2>/dev/null | tail -5
rm -rf "$WORK"
