#!/usr/bin/env python3
"""splice_report.py -- regenerate the generated parts of docs/A5_REPORT.md.

Replaces whatever sits between the `<!--STATUS-->`/`<!--/STATUS-->` and
`<!--TABLES-->`/`<!--/TABLES-->` markers with, respectively, a per-prime status
line block and the contents of code/data/tables.md (itself generated by
make_tables.py from the raw cert_<p>.out files).

Idempotent: run it as often as you like. Run make_tables.py first.

Usage:  python3 make_tables.py && python3 splice_report.py
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
DATA = os.path.join(ROOT, "code", "data")
REPORT = os.path.join(ROOT, "docs", "A5_REPORT.md")
PRIMES = [5, 13, 17, 29, 37, 41]


def between(text, a, b, new):
    i = text.index(a) + len(a)
    j = text.index(b)
    return text[:i] + "\n" + new + "\n" + text[j:]


# ---- status block ----
rows = []
ok = 0
for p in PRIMES:
    f = os.path.join(DATA, "cert_%d.out" % p)
    ff = os.path.join(DATA, "cert_%d.FAILED.out" % p)
    if os.path.exists(f):
        res = "ALL CHECKS PASS" if "ALL CHECKS PASS" in open(f).read() else "see file"
        m = re.search(r"c_2 digits \(p\^0 first, up to O\(p\^(\d+)\)\) : (\[[^\]]*\])",
                      open(f).read())
        dig = "%s digits, O(%d^%s)" % (len(m.group(2).split(",")), p, m.group(1)) if m else "?"
        rows.append("| **%d** | certified | %s | %s | `cert_%d.out` |" % (p, dig, res, p))
        ok += 1
    elif os.path.exists(ff):
        rows.append("| **%d** | **FAILED** | — | see `cert_%d.FAILED.out` | `cert_%d.FAILED.out` |"
                    % (p, p, p))
    else:
        rows.append("| **%d** | **missing** | — | no run on disk | — |" % p)

status = ["**Certificate status: %d of %d primes certified in-house.**" % (ok, len(PRIMES)), ""]
status.append("| p | `v_p(c_2(p)) = 0` | precision achieved | cross-checks C1–C7 | file |")
status.append("|---|---|---|---|---|")
status += rows
status.append("")

# control against the frozen paper
try:
    out = subprocess.run([sys.executable, os.path.join(HERE, "control_vs_paper.py")],
                         capture_output=True, text=True)
    verdict = [l for l in out.stdout.splitlines() if l.startswith("RESULT")]
    status.append("Control against the frozen `main.tex` "
                  "(`code/lpadic/control_vs_paper.py`): **%s**"
                  % (verdict[0].split(":", 1)[1].strip() if verdict else "not run"))
    status.append("")
except Exception as e:  # pragma: no cover
    status.append("Control script failed: %r" % (e,))

text = open(REPORT).read()
text = between(text, "<!--STATUS-->", "<!--/STATUS-->", "\n".join(status))
tables = open(os.path.join(DATA, "tables.md")).read()
tables = "\n".join(l for l in tables.splitlines()
                   if not l.startswith("<!-- GENERATED") and not l.startswith("# A5 tables"))
tables = ("*(Tables below are generated by `code/lpadic/make_tables.py` into\n"
          "`code/data/tables.md` and spliced in by `code/lpadic/splice_report.py`;\n"
          "no number in them is typed by hand.)*\n" + tables)
text = between(text, "<!--TABLES-->", "<!--/TABLES-->", tables)
open(REPORT, "w").write(text)
print("spliced %s" % REPORT)
