\\ m2_gtest.gp -- numerical test of (G), for E: y^2 = x^3 - 56x.
\\ ---------------------------------------------------------------------------
\\ Task C1b item 3.  (G) is the display in SINNOT_W_NOTE.md section 6.1:
\\
\\     sum_{[g] in D_E} r_{a,b}([g]; s) = (unit) . N(b-1,a)   mod m_W,
\\     independently of the fp^m-torsion translation datum s and of the level m.
\\
\\ Taking s = 0 in it, (G) is equivalent to
\\
\\     T(s) = T(0)  mod m_W,   T(s) := sum_{[g]} e*_{a,b}(psi_E(g) Omega + s, 0)/A^a ,
\\
\\ for every s in E[fp].  M1 uses (G) to refute the exponent k = 1 of
\\ hyp:sinnott(i), and more generally every presentation whose weights do not
\\ depend on the class point: it says translation is invisible modulo m_W once
\\ the class sum is taken.  Breaking it would break SINNOT_W_NOTE section 6.1.
\\
\\ HOW IT IS TESTED
\\ E[fp] is cyclic of order p, generated by s_1 = w1 conj(pi)/p with pi = a+bi the
\\ primary generator of fp (1/pi = conj(pi)/p, so s_1 generates (1/pi)Gamma/Gamma).
\\ Put D_m := T(m s_1) - T(0) for m = 1, ..., p-1 and form the monic
\\
\\     P(X) = prod_{m=1}^{p-1} (X - D_m) .
\\
\\ The D_m are algebraic numbers in the ray class field of conductor ff.fp, but
\\ P has coefficients in K = Q(i) -- the sum over D_E is Galois stable over K(ff)
\\ and Gal(K(ff.fp)/K(ff)) permutes the nonzero s -- and the run recognises them
\\ exactly.  Then, since P is monic of degree p-1,
\\
\\     every D_m lies in m_W   <=>   P(X) = X^{p-1} mod m_W
\\                             <=>   v_fp(coefficient of X^d) > 0 for all d < p-1,
\\
\\ so no Newton polygon is needed: the gate is the positivity of p-1 valuations.
\\ v_fp is computed by applying iota_p (i |-> i_p) and taking v_p in Z_p, with the
\\ fp-labelling of m2_katz.gp.  The run also prints v_fp of the constant term,
\\ which is (p-1) times the common valuation of the D_m when the Newton polygon
\\ is a single segment, as it is at every slot below.
\\
\\ The six slots are those of eq:jetpackage, in the closed forms eq:EKclosed; the
\\ untranslated values T(0) are the S_{a,b} table of numerics.tex divided by the
\\ appropriate power of A, and the run checks each against that table.
\\
\\ Run from this directory:   gp -q m2_gtest.gp        (about 2.5 minutes at p = 13)
\\ Parameters from the environment:
\\     GTP     the split prime                   default 13
\\     GTPREC  realprecision                     default 500
\\     GTOUT   output file                       default m2_gtest.out
\\ Cost is O(p) class sums of 384 terms, so p = 29 costs about twice p = 13.
\\ ---------------------------------------------------------------------------

default(parisizemax, 6000000000);
getdef(name, dflt) = { my(s = getenv(name)); if(type(s) == "t_STR" && s != "", s, dflt) };
P    = eval(getdef("GTP", "13"));
PREC = eval(getdef("GTPREC", "500"));
OUT  = getdef("GTOUT", "m2_gtest.out");
default(realprecision, PREC);

E = ellinit([0,0,0,-56,0]); w1 = E.omega[1]; A = w1^2/Pi;
NGATE = 0; NGTOT = 0;
system(Str("rm -f ", OUT));
say(s) = { print(s); write(OUT, s); };
gate(name, ok) = { NGTOT++; if(ok, NGATE++); say(Str(name, if(ok, "PASS", "FAIL"))); };

say("=== m2_gtest.gp : numerical test of (G), SINNOT_W_NOTE section 6.1 ===");
say(Str("pari version      : ", version()));
say("curve             : E : y^2 = x^3 - 56x   [0,0,0,-56,0],  ff = (56)");
say(Str("realprecision     : ", default(realprecision), "   prime p = ", P));

isprimary(a,b) = ((a+b-1) % 4 == 0) && ((b-a+1) % 4 == 0);
classid(a,b)   = ((a % 56) + 56) % 56 * 56 + ((b % 56) + 56) % 56;
epstab = vector(56*56); QF = Qfb(1,0,1);
{forprime(q = 5, 60000,
  if(q % 4 != 1 || q == 7, next);
  my(sol = qfbsolve(QF,q)); if(sol == 0, next);
  my(a = sol[1], b = sol[2], fa = 0, fb = 0);
  for(k = 0, 3, if(isprimary(a,b), fa = a; fb = b; break); [a,b] = [-b,a]);
  my(ap = ellap(E,q), cand = [2*fa,-2*fb,-2*fa,2*fb], kk = 0, nm = 0);
  for(k = 1, 4, if(cand[k] == ap, kk = k; nm++));
  if(nm != 1, next);
  my(id = classid(fa,fb)); if(epstab[id] == 0, epstab[id] = kk));}
CA = List(); CB = List(); CK = List();
{for(a = 0, 55, for(b = 0, 55,
  if(!isprimary(a,b), next); if((a+b) % 2 == 0, next);
  if(a % 7 == 0 && b % 7 == 0, next);
  my(id = classid(a,b)); if(epstab[id] == 0, next);
  listput(CA,a); listput(CB,b); listput(CK, epstab[id]-1)));}
NC = #CA;
say(Str("classes of D_E    : ", NC));
gate("384 classes      : ", NC == 384);

\\ the fp-labelling of m2_katz.gp
{my(sol = qfbsolve(QF,P), a = sol[1], b = sol[2], fa = 0, fb = 0);
 for(k = 0, 3, if(isprimary(a,b), fa = a; fb = b; break); [a,b] = [-b,a]);
 if(fb < 0, fb = -fb); GA = fa; GB = fb;}
IPM = lift(Mod(-GA,P)/Mod(GB,P));
IP  = sqrt(-1 + O(P^60)); if(lift(IP + O(P^1)) != IPM, IP = -IP);
S1  = w1*conj(GA + GB*I)/P;
say(Str("fp = (", GA, " + ", GB, "i)   iota_p : i -> ", IPM, " mod ", P));
say(Str("E[fp] generator   : s_1 = w1 conj(pi)/p ;  p.s_1/w1 = conj(pi) : ",
        abs(P*S1/w1 - conj(GA + GB*I)) < 10^(-100)));
gate("E[fp] generator  : ", abs(P*S1/w1 - conj(GA + GB*I)) < 10^(-100));

\\ class parameters psi_E(g) Omega = eps(g) t_g  (SINNOT_W_NOTE (P))
CP = vector(NC);
{for(j = 1, NC, CP[j] = I^CK[j] * (CA[j] + CB[j]*I)*w1/56);}

rec(x) = {
  my(re = bestappr(real(x), 10^250), im = bestappr(imag(x), 10^250));
  my(err = abs(x - (re + im*I)));
  [re, im, if(err == 0, -oo, exponent(err))];
};
vfp(re, im) = { my(z = re + im*IP); if(z == 0, oo, valuation(z, P)); };

E1s(z) = ellzeta(E,z) - conj(z)/A;

runslot(nm, f, T0) = {
  my(T = vector(P), poly = 1, ok = 1, allpos = 1, t0 = getabstime());
  for(m = 0, P-1,
    my(s = m*S1, acc = 0);
    for(j = 1, NC, acc += f(CP[j] + s));
    T[m+1] = acc);
  my(r0 = rec(T[1]));
  my(t0ok = (abs(T[1] - T0) == 0) || (exponent(abs(T[1] - T0)) < -1000));
  say("");
  say(Str("--- ", nm, " ---"));
  say(Str("  T(0) = ", r0[1], if(r0[2] == 0, "", Str(" + (", r0[2], ")i")),
          "   residual 2^", r0[3],
          "   matches the numerics.tex table : ", t0ok));
  for(m = 1, P-1, poly *= ('X - (T[m+1] - T0)));
  my(s = "  v_fp of the coefficient of X^d, d = 0..", vs = vector(P-1));
  for(d = 0, P-2,
    my(r = rec(polcoef(poly, d, 'X)));
    if(r[3] > -300, ok = 0);
    vs[d+1] = vfp(r[1], r[2]);
    if(vs[d+1] <= 0, allpos = 0));
  my(line = "   ");
  for(d = 0, P-2, line = Str(line, "[", d, ":", vs[d+1], "] "));
  say(Str(s, P-2, " :"));
  say(line);
  say(Str("  all coefficients recognised exactly : ", ok));
  say(Str("  P(X) = X^", P-1, " mod m_W (every D_m in m_W) : ", allpos));
  say(Str("  v_fp(constant term) = ", vs[1],
          " , so the common v(D_m) = ", vs[1], "/", P-1,
          " if the Newton polygon is one segment"));
  say(Str("  (", round((getabstime()-t0)/100)/10., " s)"));
  gate(Str("  ", nm, " : "), ok && allpos && t0ok);
};

say("");
say("--- (G) at the six slots of eq:jetpackage ---");
say("D_m = T(m s_1) - T(0), m = 1..p-1;  (G) says every D_m lies in m_W.");
runslot("(a,b)=(0,1)  e*_{0,1} = E1*", z -> E1s(z), 0);
runslot("(a,b)=(0,2)  e*_{0,2} = wp", z -> ellwp(E,z), 3584);
runslot("(a,b)=(1,1)  e*_{1,1}/A = -(E1*^2-wp)/2", z -> -(E1s(z)^2 - ellwp(E,z))/2, 32);
runslot("(a,b)=(0,3)  e*_{0,3} = -wp'/2", z -> -ellwp(E,z,1)[2]/2, 225792);
{runslot("(a,b)=(1,2)  e*_{1,2}/A = -(E1* wp + wp'/2)",
         z -> my(w = ellwp(E,z,1)); -(E1s(z)*w[1] + w[2]/2), 0);}
{runslot("(a,b)=(2,1)  e*_{2,1}/A^2 = (E1*^3-3E1*wp-wp')/3",
         z -> my(w = ellwp(E,z,1)); (E1s(z)^3 - 3*E1s(z)*w[1] - w[2])/3, -144);}

say("");
say(Str("gates passed      : ", NGATE, " of ", NGTOT));
{if(NGATE == NGTOT, print("M2GTESTDONE"), print("M2GTESTINCOMPLETE"));}
quit
