default(parisizemax,800000000);
E0 = ellinit([0,0,0,-56,0]);
E = ellminimalmodel(E0, &cv);
print("minimal a-invariants: ", [E.a1,E.a2,E.a3,E.a4,E.a6]);
gr = ellglobalred(E); N = gr[1];
print("conductor = ", factor(N), "  disc = ", factor(abs(E.disc)), "  tamagawa = ", gr[3]);
print("torsion: ", elltors(E)[2], "   rootno = ", ellrootno(E));
Q1 = ellchangepoint([-7,7], cv); Q2 = ellchangepoint([8,8], cv);
print("Q1 on E: ", ellisoncurve(E,Q1), "  Q2 on E: ", ellisoncurve(E,Q2));
rk = ellrank(E);
print("ellrank: ", rk[1..3]);
M = ellheightmatrix(E,[Q1,Q2]); Reg = matdet(M);
print("arch Reg(Q1,Q2) = ", Reg);
iferr(sat = ellsaturation(E,[Q1,Q2],500); print("saturation: index^2 vs (Q1,Q2) = ", Reg/matdet(ellheightmatrix(E,sat))), err, print("saturation call issue: ", err));
ar = ellanalyticrank(E);
print("analytic rank data: ", ar);
om = if(E.disc > 0, 2*real(E.omega[1]), real(E.omega[1]));
shaan = ar[2]*elltors(E)[1]^2/(om*Reg*vecprod(gr[3]));
print("Sha_an (w.r.t. Q1,Q2) = ", shaan);
print("a_p for split p<60: ", [[p,ellap(E,p)] | p<-primes(20), p%4==1 && N%p!=0]);
gettime();
R1 = ellpadicregulator(E,101,6,[Q1,Q2]); t1 = gettime();
print("p=101: vReg=", valuation(R1,101), "  time=", t1, "ms");
R2 = ellpadicregulator(E,1009,6,[Q1,Q2]); t2 = gettime();
print("p=1009: vReg=", valuation(R2,1009), "  time=", t2, "ms");
R3 = ellpadicregulator(E,2017,5,[Q1,Q2]); t3 = gettime();
print("p=2017: vReg=", valuation(R3,2017), "  time=", t3, "ms");
print("QUICKDONE");
quit
