import Mathlib

/-!
# Grading-valuation kernel)

This file proves, as pure `mathlib`-only algebra over an **abstract local
domain**, the valuation step of the paper's Proposition 7.2(2). Nothing here
mentions the paper's interface (`KatzData` is *not* imported): the argument is
carried over a bare local domain `W` with a chosen generator `ϖ` of its maximal
ideal, so that the instantiation `ϖ := (p : W)` performed by Theorem C (Theorem 7.10) is
a purely downstream substitution with no char-`p` pathology to
worry about.

## Mathematical content

The paper's grade-two divisibility gives a congruence
`ϖ² · (κ₀ · c − m) ∈ (ϖ³)` for a unit `κ₀`, where `c = c₂(L^K)` is the grade-two
coefficient and `m = m2core` is the `ϖ⁻²`-lift of the grade-two moment sum. In
the domain `W` we may cancel `ϖ²`, obtaining `κ₀ · c − m ∈ (ϖ) = 𝔪_W`. Since
`(ϖ) = 𝔪_W = ker(residue)`, the residues of `κ₀ · c` and `m` agree; and the
local-ring dictionary `IsUnit x ↔ residue x ≠ 0` together with `IsUnit (κ₀·c) ↔
IsUnit c` (`κ₀` a unit) turns this into the criterion
`IsUnit c ↔ residue W m ≠ 0`. Here `residue W m` is exactly the **criterion
class** `𝔠(𝔭)` of `KatzData.criterionClass`, so the headline consumes
the `grading_congr` field verbatim.

## Main results

* `FinShaRank2.dvd_of_pow_mul_mem_span_pow_succ` — the **divided-congruence
  helper** (general exponent `k`): in a domain, `ϖ^k · a ∈ (ϖ^(k+1))` implies
  `a ∈ (ϖ)`. Reusable by `thm_reduction`.
* `FinShaRank2.isUnit_iff_residue_ne_zero_of_grading_congr` — the **headline**:
  from the `grading_congr`-shaped hypothesis, `IsUnit c ↔ residue W m ≠ 0`.

The residue/unit dictionary itself is not re-proved here: the pin already
provides one-step forms `IsLocalRing.residue_eq_zero_iff` and
`IsLocalRing.residue_ne_zero_iff_isUnit`
(`Mathlib.RingTheory.LocalRing.ResidueField.Basic`), which the headline uses
directly.
-/

namespace FinShaRank2

/-- **Divided-congruence helper** (general exponent `k`). In an integral domain,
if `ϖ^k · a` lies in the ideal `(ϖ^(k+1))` then `a` lies in `(ϖ)`.

The proof cancels the nonzero factor `ϖ^k` (using `ϖ ≠ 0` and the domain
hypothesis): writing `ϖ^k · a = ϖ^(k+1) · y = ϖ^k · (ϖ · y)` and cancelling
gives `a = ϖ · y`, i.e. `ϖ ∣ a`.

This is the algebraic engine of Proposition 7.2(2) (used at `k = 2`); it is kept
in the general form so that `thm_reduction` may reuse it at other jet grades. -/
theorem dvd_of_pow_mul_mem_span_pow_succ {W : Type*} [CommRing W] [IsDomain W]
    {ϖ : W} (hϖ : ϖ ≠ 0) (k : ℕ) (a : W)
    (h : ϖ ^ k * a ∈ Ideal.span {ϖ ^ (k + 1)}) : a ∈ Ideal.span {ϖ} := by
  rw [Ideal.mem_span_singleton] at h ⊢
  obtain ⟨y, hy⟩ := h
  refine ⟨y, ?_⟩
  apply mul_left_cancel₀ (pow_ne_zero k hϖ)
  rw [hy]
  ring

/-- **Grading-valuation criterion** (Proposition 7.2(2)), abstract local-domain
form. Let `W` be a local integral domain whose maximal ideal is generated by a
nonzero element `ϖ`. Given a unit `κ₀ : Wˣ` and `c m : W` with the grade-two
congruence `ϖ² · (κ₀ · c − m) ∈ (ϖ³)`, the coefficient `c` is a unit precisely
when the residue of `m` is nonzero:

`IsUnit c ↔ IsLocalRing.residue W m ≠ 0`.

Task `thm_reduction` instantiates `ϖ := (p : W)` (with `ϖ ≠ 0` from injectivity of
`algebraMap ℤ_[p] W`), `hmax := KatzData.maxIdeal_eq_p`, `c := coeff 2 LKatz`,
`m := m2core`, and reads `κ₀`/the congruence off the `KatzData.grading_congr`
field; the right-hand side `residue W m` is then `KatzData.criterionClass`.

The generator `ϖ` is left implicit so that it is inferred from `hmax` at the
call site, making the composition with `grading_congr` friction-free. -/
theorem isUnit_iff_residue_ne_zero_of_grading_congr {W : Type*} [CommRing W]
    [IsDomain W] [IsLocalRing W] {ϖ : W}
    (hmax : IsLocalRing.maximalIdeal W = Ideal.span {ϖ}) (hϖ : ϖ ≠ 0)
    (κ₀ : Wˣ) (c m : W)
    (hcong : ϖ ^ 2 * ((κ₀ : W) * c - m) ∈ Ideal.span {ϖ ^ 3}) :
    IsUnit c ↔ IsLocalRing.residue W m ≠ 0 := by
  -- Cancel `ϖ²`: the difference `κ₀·c − m` lands in `(ϖ) = 𝔪_W`.
  have hmem : (κ₀ : W) * c - m ∈ IsLocalRing.maximalIdeal W := by
    rw [hmax]
    exact dvd_of_pow_mul_mem_span_pow_succ hϖ 2 _ hcong
  -- Hence `residue (κ₀·c) = residue m`.
  have hres : IsLocalRing.residue W ((κ₀ : W) * c) = IsLocalRing.residue W m := by
    rw [← sub_eq_zero, ← map_sub, IsLocalRing.residue_eq_zero_iff]
    exact hmem
  -- Local-ring dictionary + unit multiple close the chain.
  rw [← hres, IsLocalRing.residue_ne_zero_iff_isUnit, Units.isUnit_units_mul]

end FinShaRank2
