import Mathlib
import FinShaRank2.Defs
import FinShaRank2.Interface.EK

/-!
# Katz interface: `KatzData p` + `SinnottHyp` (task T13)

The Katz-measure / Eisenstein–Kronecker layer of the assumption surface for
*Horizontal rigidity for second jets of Katz p-adic L-functions, with
applications to the Tate–Shafarevich group in rank two* (paper §`sec:deltaE`).

`KatzData p Lp` packages the algebraic phase of the programme:

* the comparison `L_p(E,T) = c_p · u(T) · L^{Katz}_𝔭(T)` (`lem:comparison`);
* the grading congruence reducing `v_p(c₂(L^K)) = 0` to nonvanishing of the
  mod-𝔭 **criterion class** built from grade-two moments (`prop:jetformula`,
  `prop:grading`);
* the mod-𝔭 Sinnott trace `traceClass`.

The candidate invariant `δ_E(c)` is no longer a field of this structure. It is
the def `EKPackage.deltaE` of `Interface/EK.lean`, computed from the divisor
`D_E`, the package `𝓡_E` and the coefficient vector `c`; `SinnottHyp` below
carries the package and the vector, and `thm:reduction` routes the resultant
step through `Kernel/Resultant.forall_eq_one_of_prod_eq_one`.

## Epistemic split (board §1 — load-bearing)

`KatzData` is an **instantiable** structure: every field is either citable
classical mathematics, a data equation, or an *opaque* predicate whose
truth is never asserted here. The conjectural content of the paper —
`hyp:sinnott`, `conj:EK` — is kept OUT of `KatzData` and lives only in
`SinnottHyp` (a `Prop`-valued structure used in **hypothesis position** of
`thm:reduction`) and in the hypothesis `δ_E(c) ≠ 0` of `thm:reduction`.
`SinnottHyp` is referenced by nothing instantiable.

The bridge `criterionClass` between `KatzData` and `SinnottHyp` is a **def**
(not a field): `criterionClass K := IsLocalRing.residue K.W K.m2core`.

## The valuation normalisation is multiplicative

`SinnottHyp` below states `hyp:sinnott`'s integrality and nonvanishing clauses
through the multiplicative valuation `P.v p` of `EKPackage`. Mathlib's
`Valuation L Γ` is a monoid-with-zero hom into a linearly ordered commutative
monoid with zero, so the order runs opposite to the paper's additive `v_𝔭`:

| paper (`v_𝔭`, additive) | Lean (`P.v p`, multiplicative) |
|---|---|
| `v_𝔭(x) ≥ 0` (`x` is `𝔭`-integral) | `P.v p x ≤ 1` |
| `v_𝔭(x) = 0` (`𝔭 ∤ x`) | `P.v p x = 1` |

The same dictionary is stated in `Interface/EK.lean` and in
`Kernel/Resultant.lean`; this is the third place a reader meets it.

## Threading of `Lp` (contract for T14)

`Lp : Λ p` is a **structure parameter** of `KatzData` (matching the sibling
`IwasawaData`/`AnalyticData` convention). `PrimeData` (T14) instantiates
`KatzData p Lp` at the *same* `Lp` it feeds `AnalyticData`, so `comparison`
relates the genuine MTT `L_p` to `LKatz` with no divergent copy and no
tie-equation needed. `SinnottHyp` and `criterionClass` carry `Lp` accordingly.

Paper labels quoted below: `lem:comparison`, `prop:jetformula`, `prop:grading`,
`lem:decoupling`, `def:deltaE`, `hyp:sinnott`, `conj:EK`, `thm:reduction`.
-/

open PowerSeries

namespace FinShaRank2

/-- **Katz data at a split prime `p`** (paper §`sec:deltaE`), relative to the MTT
p-adic L-function `Lp : Λ p`.

The coefficient ring `W` is the completion of the maximal unramified extension
of `ℤ_[p]` (`main.tex` §`sec:deltaE` preamble): a local domain, `ℤ_[p]`-algebra,
with maximal ideal generated by `p`. Its instances are bundled as fields and
re-exported as instances by the `attribute [instance]` line below, so `K.W`
carries `CommRing`/`IsDomain`/`IsLocalRing`/`Algebra ℤ_[p]` everywhere. -/
structure KatzData (p : ℕ) [Fact p.Prime] (Lp : Λ p) where
  /-- The coefficient ring `W` = completion of the maximal unramified extension
  of `ℤ_[p]` (`main.tex` §`sec:deltaE`: "`W` denotes the completion of the
  maximal unramified extension of `ℤ_[p]`").
  SOURCE: de Shalit [E. de Shalit, *Iwasawa theory of elliptic curves with
  complex multiplication. p-adic L functions*, Perspectives in Mathematics 3,
  Academic Press, Boston, MA, 1987], II.
  PAPER: §`sec:deltaE` preamble. STATUS: data. -/
  W : Type
  /-- `W` is a commutative ring. STATUS: classical (structure instance). -/
  [commRing : CommRing W]
  /-- `W` is an integral domain (needed for the `p²`-cancellation in
  `grading_congr` and for `X_prime`-style facts downstream).
  STATUS: classical (structure instance). -/
  [isDomain : IsDomain W]
  /-- `W` is a local ring; its residue field carries the criterion/Sinnott
  classes. STATUS: classical (structure instance). -/
  [isLocalRing : IsLocalRing W]
  /-- `W` is a `ℤ_[p]`-algebra; `algebraMap ℤ_[p] W` is the base map along which
  `Lp` is compared with `LKatz`. STATUS: classical (structure instance). -/
  [algebra : Algebra ℤ_[p] W]
  /-- `algebraMap ℤ_[p] W` is **injective** (`W` is a faithful unramified
  extension of `ℤ_[p]`).
  SOURCE: de Shalit [op. cit.], II (`W` ⊇ `ℤ_[p]`).
  PAPER: §`sec:deltaE` preamble. STATUS: classical. -/
  algInj : Function.Injective (algebraMap ℤ_[p] W)
  /-- The maximal ideal of `W` is generated by `p` (`W` unramified over `ℤ_[p]`,
  so ramification index `1`).
  SOURCE: de Shalit [op. cit.], II; standard unramified local ring theory.
  PAPER: §`sec:deltaE` preamble. STATUS: classical. -/
  maxIdeal_eq_p : IsLocalRing.maximalIdeal W = Ideal.span {(p : W)}
  /-- `L^{Katz}_𝔭(T) ∈ W⟦T⟧`: the one-variable restriction of the Katz measure
  `μ_{𝔣𝔭^∞}` to the cyclotomic line through the central character of `ψ_E`
  (`L^K` of `prop:jetformula`; `L^{Katz}_𝔭` of `lem:comparison`).
  SOURCE: Katz [N. M. Katz, *p-adic interpolation of real analytic Eisenstein
  series*, Ann. of Math. (2) 104 (1976), 459–571]; Bannai–Kobayashi (BK3).
  PAPER: `lem:comparison`, `prop:jetformula`. STATUS: data. -/
  LKatz : PowerSeries W
  /-- **Comparison** (`lem:comparison`): after base change to `W`, the MTT
  p-adic L-function equals `c_p · u(T) · L^{Katz}_𝔭(T)` for a unit constant
  `c ∈ Wˣ` and a unit series `u ∈ (W⟦T⟧)ˣ`.

  The paper's `c_p ∈ 𝐐̄_p^×` is taken here already inside `W` and as a **unit**:
  this bakes in the conclusion `v_p(c_p) = 0` for `p ∉ S` (`lem:comparison`,
  where the exceptional set for `c_p`-unit-ness is folded into `S`; for the
  testbed the period ratio is supported on `{2,7}`, so `v_p(c_p) = 0` at every
  split `p`).
  SOURCE: Bannai–Kobayashi Cor. 3.12 [K. Bannai and S. Kobayashi, *Algebraic
  theta functions and the p-adic interpolation of Eisenstein–Kronecker
  numbers*, Duke Math. J. 153 (2010), no. 2, 229–295] + de Shalit II §4
  [op. cit.] for the local terms.
  PAPER: `lem:comparison` (`L_p(E,T) = c_p · u(T) · L^{Katz}_𝔭(T)`).
  STATUS: classical (consequence-form: `c`, `u` taken as units). -/
  comparison : ∃ (c : Wˣ) (u : (PowerSeries W)ˣ),
      Lp.map (algebraMap ℤ_[p] W) = (c : W) • ((u : PowerSeries W) * LKatz)
  /-- The **grade-two core** `m2core ∈ W`: the `p^{-2}` lift of the grade-two
  moment sum, `M₂(𝔭) = p² · m2core` (`prop:grading`(2) divisibility
  `v_p(M₂(𝔭)) ≥ 2`). Its residue mod 𝔭 is the criterion class `𝔠(𝔭)`
  (`criterionClass`).
  SOURCE: `prop:grading`(2) (`M₂(𝔭) = p² · (𝔠(𝔭)-lift)`); de Shalit II §4 for
  the local moment terms.
  PAPER: `prop:grading`(2). STATUS: data. -/
  m2core : W
  /-- **Grading congruence** (`prop:jetformula` + `prop:grading`(1)): for a unit
  normalisation `κ₀ ∈ Wˣ` (absorbing `2 log_p(1+p)²`),
  `p² · (κ₀ · c₂(L^K) − m2core) ∈ (p³)`,
  i.e. `κ₀ · coeff 2 LKatz ≡ m2core (mod p)` after cancelling `p²` in the domain
  `W`. This is exactly the hypothesis of the abstract grading-valuation kernel
  (T25), which turns it into `IsUnit (coeff 2 LKatz) ↔ 𝔠(𝔭) ≠ 0`.

  **Honest descope.** `prop:jetformula` expresses `c₂(L^K) = ½∫m² dμ_ψ` as a
  second moment and `prop:grading`(1) gives `2 log_p(1+p)² c₂(L^K) ≡ M₂(𝔭)
  (mod p³ W)`; the Eisenstein–Kronecker bookkeeping identifying `M₂(𝔭)`/`m2core`
  "to the last constant" (`hyp:sinnott`(i)) is **not** carried in Lean. This
  field records only the resulting algebraic congruence between `coeff 2 LKatz`
  and `m2core`.
  SOURCE: Bannai–Kobayashi Prop. 3.3 / Thm. 3.7 [Duke Math. J. 153 (2010),
  229–295] (moment ↔ Eisenstein–Kronecker display) + de Shalit II §4.
  PAPER: `prop:jetformula`, `prop:grading`(1). STATUS: consequence-form. -/
  grading_congr : ∃ κ₀ : Wˣ,
      (p : W) ^ 2 * ((κ₀ : W) * coeff 2 LKatz - m2core) ∈ Ideal.span {(p : W) ^ 3}
  /-- The **mod-𝔭 Sinnott trace** `traceClass ∈ residue field of W` (opaque
  data): the trace, over the 𝔭-torsion translates of `ssec:moments`, of the
  reductions of the fixed grade-two combination of the sections `𝓡_E`. Its
  equality with `criterionClass` is `hyp:sinnott`(i) (a `SinnottHyp` field, not
  asserted here); its nonvanishing under pointwise `𝔭`-unitness of `F_c` on
  `D_E` is `hyp:sinnott`(ii).
  SOURCE: Bannai–Kobayashi §§2–3 calculus [Duke Math. J. 153 (2010), 229–295]
  (the second-order Kummer-congruence analysis of the p-adic theta expansion).
  PAPER: `hyp:sinnott`, §`ssec:moments`. STATUS: opaque data. -/
  traceClass : IsLocalRing.ResidueField W

attribute [instance] KatzData.commRing KatzData.isDomain KatzData.isLocalRing
  KatzData.algebra

namespace KatzData

variable {p : ℕ} [Fact p.Prime] {Lp : Λ p}

/-- The **criterion class** `𝔠(𝔭) = p^{-2} M₂(𝔭) mod 𝔭 ∈ residue field of W`
of `prop:grading`, as the residue of `m2core`.

This is a **def, not a field** (board §1 epistemic split): it is the bridge
that `SinnottHyp.presentation` (`hyp:sinnott`(i)) equates with the constructed
`traceClass`, and the object the grading-valuation kernel (T25) links to
`IsUnit (coeff 2 LKatz)`.
PAPER: `prop:grading` (the criterion class `𝔠(𝔭)`). -/
noncomputable def criterionClass (K : KatzData p Lp) : IsLocalRing.ResidueField K.W :=
  IsLocalRing.residue K.W K.m2core

/-- `algebraMap ℤ_[p] K.W` is a **local ring homomorphism**, derived from
`maxIdeal_eq_p`: a non-unit of `ℤ_[p]` lies in `(p) = maximalIdeal ℤ_[p]`, so
its image lies in `(p) = maximalIdeal K.W`, hence is a non-unit.

Provided so that the unit-transfer step of `thm:reduction` (T22/T33) —
`IsUnit (coeff 2 (Lp.map (algebraMap ℤ_[p] W))) ↔ IsUnit (coeff 2 Lp)` via
`isUnit_map_iff` — has its `[IsLocalHom …]` instance ready without expanding
`KatzData`'s field list.
SOURCE: derived from `maxIdeal_eq_p` + `PadicInt.maximalIdeal_eq_span_p`. -/
theorem algMap_isLocalHom (K : KatzData p Lp) : IsLocalHom (algebraMap ℤ_[p] K.W) := by
  refine ⟨fun {a} ha => ?_⟩
  by_contra hna
  have hmem : a ∈ IsLocalRing.maximalIdeal ℤ_[p] :=
    (IsLocalRing.mem_maximalIdeal a).mpr (mem_nonunits_iff.mpr hna)
  rw [PadicInt.maximalIdeal_eq_span_p, Ideal.mem_span_singleton] at hmem
  obtain ⟨b, rfl⟩ := hmem
  have hu : IsUnit ((p : K.W) * algebraMap ℤ_[p] K.W b) := by
    simpa [map_mul, map_natCast] using ha
  have hp : (p : K.W) ∈ IsLocalRing.maximalIdeal K.W := by
    rw [K.maxIdeal_eq_p, Ideal.mem_span_singleton]
  exact (mem_nonunits_iff.mp ((IsLocalRing.mem_maximalIdeal _).mp hp))
    (isUnit_of_mul_isUnit_left hu)

end KatzData

/-- **Sinnott trace property for second jets** (`hyp:sinnott`) — a
`Prop`-valued structure used ONLY in **hypothesis position** of `thm:reduction`
(board §1 epistemic split). It is referenced by no instantiable structure, so
the conjectural content never leaks into the assumption surface.

It is stated for a `KatzData` at `p` together with the Eisenstein–Kronecker
package `P` and the coefficient vector `c` of `hyp:sinnott`(i), so that the
values `F_c(t)` the hypothesis speaks about are the `EKPackage.Fc` of
`Interface/EK.lean` rather than an opaque predicate.

The three fields are the paper's own clauses: -/
structure SinnottHyp (p : ℕ) [Fact p.Prime] (Lp : Λ p) (Kd : KatzData p Lp)
    (P : EKPackage) (c : Fin 6 → P.K) : Prop where
  /-- **`hyp:sinnott`(i), integrality clause.** The values `F_c(t)`, `t ∈ D_E`,
  are `𝔭`-integral: in the paper `v_𝔭(F_c(t)) ≥ 0`, here `P.v p (P.Fc c t) ≤ 1`
  (the multiplicative normalisation of the module docstring).

  This clause sits in hypothesis position, which is where the paper puts it. In
  the structure this file replaces it was baked into the `KatzData` field
  `resultant_link`, an unproved implication carried on the instantiable
  assumption surface under `STATUS: classical`.
  PAPER: `hyp:sinnott`(i). -/
  integral : ∀ t ∈ P.D, P.v p (P.Fc c t) ≤ 1
  /-- **`hyp:sinnott`(i), presentation clause.** The criterion class `𝔠(𝔭)` of
  `prop:grading` admits the presentation constructed in §`ssec:moments`: it is
  the mod-𝔭 trace `traceClass` of the reductions of the combination `F_c` of the
  sections `𝓡_E`, weighted over the `𝔭^k`-torsion translation data. (Bannai–
  Kobayashi calculus bookkeeping — expected provable, stated as hypothesis
  because the bookkeeping is not carried to the last constant.)
  PAPER: `hyp:sinnott`(i). -/
  presentation : IsLocalRing.residue Kd.W Kd.m2core = Kd.traceClass
  /-- **`hyp:sinnott`(ii) (Nonvanishing).** If `F_c` is a `𝔭`-unit at every point
  of `D_E` — the paper's `v_𝔭(F_c(t)) = 0` for all `t ∈ D_E`, here
  `P.v p (P.Fc c t) = 1` — then the trace `traceClass` is nonzero: passing to
  the level-`p` trace introduces no new zeros beyond those detected by
  `δ_E(c)`. The genuine jet-level analogue of Sinnott's lemma.

  The antecedent is the paper's explicit pointwise condition; the structure this
  file replaces stated it as an opaque `Prop` field of `KatzData`.
  PAPER: `hyp:sinnott`(ii). -/
  nonvanishing : (∀ t ∈ P.D, P.v p (P.Fc c t) = 1) → Kd.traceClass ≠ 0

end FinShaRank2
