import Mathlib
import FinShaRank2.Defs

/-!
# Katz interface: `KatzData p`

The Katz-measure layer of the assumption surface for
*Second derivatives of p-adic L-functions and the Shafarevich–Tate group of
rank-two CM elliptic curves*.

`KatzData p Lp` packages the algebraic phase of the programme:

* the comparison `L_p(E,T) = c_p · u(T) · L^{Katz}_𝔭(T)` (Lemma 3.5), which
  Lemma 6.3 reads grade by grade;
* the grading congruence reducing `v_p(c₂(L^K)) = 0` to nonvanishing of the
  mod-𝔭 **criterion class** built from grade-two moments (Proposition 6.1,
  Proposition 6.2).

## Epistemic split

`KatzData` is an **instantiable** structure: every field is either citable
classical mathematics, a data equation, or an *opaque* predicate whose
truth is never asserted here. No conjectural statement is a field of it.

The criterion class of Proposition 6.2 is a **def** (not a field):
`criterionClass K := IsLocalRing.residue K.W K.m2core`.

## Threading of `Lp` (contract for `ClassicalInputs`)

`Lp : Λ p` is a **structure parameter** of `KatzData` (matching the sibling
`IwasawaData`/`AnalyticData` convention). `PrimeData` (`ClassicalInputs`) instantiates
`KatzData p Lp` at the *same* `Lp` it feeds `AnalyticData`, so `comparison`
relates the genuine MTT `L_p` to `LKatz` with no divergent copy and no
tie-equation needed. `criterionClass` carries `Lp` accordingly.

Paper statements quoted below: Lemma 3.5, Proposition 6.1, Proposition 6.2,
Lemma 6.3.
-/

open PowerSeries

namespace FinShaRank2

/-- **Katz data at a split prime `p`** (the Katz measure of §2.3), relative to the MTT
p-adic L-function `Lp : Λ p`.

The coefficient ring `W` is the completion of the maximal unramified extension
of `ℤ_[p]` (§2.3): a local domain, `ℤ_[p]`-algebra,
with maximal ideal generated by `p`. Its instances are bundled as fields and
re-exported as instances by the `attribute [instance]` line below, so `K.W`
carries `CommRing`/`IsDomain`/`IsLocalRing`/`Algebra ℤ_[p]` everywhere. -/
structure KatzData (p : ℕ) [Fact p.Prime] (Lp : Λ p) where
  /-- The coefficient ring `W` = completion of the maximal unramified extension
  of `ℤ_[p]` (§2.3: "`W` denotes the completion of the
  maximal unramified extension of `ℤ_[p]`").
  SOURCE: de Shalit [E. de Shalit, *Iwasawa theory of elliptic curves with
  complex multiplication. p-adic L functions*, Perspectives in Mathematics 3,
  Academic Press, Boston, MA, 1987], II.
  PAPER: §2.3 (`ssec:katz`). STATUS: data. -/
  W : Type
  /-- `W` is a commutative ring. STATUS: classical (structure instance). -/
  [commRing : CommRing W]
  /-- `W` is an integral domain (needed for the `p²`-cancellation in
  `grading_congr` and for `X_prime`-style facts downstream).
  STATUS: classical (structure instance). -/
  [isDomain : IsDomain W]
  /-- `W` is a local ring; its residue field carries the criterion/Sinnott
  classes. STATUS: classical (structure instance). -/
  [isLocalRing : IsLocalRing W]
  /-- `W` is a `ℤ_[p]`-algebra; `algebraMap ℤ_[p] W` is the base map along which
  `Lp` is compared with `LKatz`. STATUS: classical (structure instance). -/
  [algebra : Algebra ℤ_[p] W]
  /-- `algebraMap ℤ_[p] W` is **injective** (`W` is a faithful unramified
  extension of `ℤ_[p]`).
  SOURCE: de Shalit [op. cit.], II (`W` ⊇ `ℤ_[p]`).
  PAPER: §2.3 (`ssec:katz`). STATUS: classical. -/
  algInj : Function.Injective (algebraMap ℤ_[p] W)
  /-- The maximal ideal of `W` is generated by `p` (`W` unramified over `ℤ_[p]`,
  so ramification index `1`).
  SOURCE: de Shalit [op. cit.], II; standard unramified local ring theory.
  PAPER: §2.3 (`ssec:katz`). STATUS: classical. -/
  maxIdeal_eq_p : IsLocalRing.maximalIdeal W = Ideal.span {(p : W)}
  /-- `L^{Katz}_𝔭(T) ∈ W⟦T⟧`: the one-variable restriction of the Katz measure
  `μ_{𝔣𝔭^∞}` to the cyclotomic line through the central character of `ψ_E`
  (`L^K` of Proposition 6.1; `L^{Katz}_𝔭` of Lemma 3.5).
  SOURCE: Katz [N. M. Katz, *p-adic interpolation of real analytic Eisenstein
  series*, Ann. of Math. (2) 104 (1976), 459–571]; Bannai–Kobayashi (BK3).
  PAPER: Lemma 3.5 (`lem:comparison`), Proposition 6.1 (`prop:jetformula`). STATUS: data. -/
  LKatz : PowerSeries W
  /-- **Comparison** (Lemma 3.5): after base change to `W`, the MTT
  p-adic L-function equals `c_p · u(T) · L^{Katz}_𝔭(T)` for a unit constant
  `c ∈ Wˣ` and a unit series `u ∈ (W⟦T⟧)ˣ`.

  The paper's `c_p ∈ 𝐐̄_p^×` is taken here already inside `W` and as a **unit**:
  this bakes in the conclusion `v_p(c_p) = 0` for `p ∉ S` (Lemma 3.5,
  where the exceptional set for `c_p`-unit-ness is folded into `S`; for the
  testbed the period ratio is supported on `{2,7}`, so `v_p(c_p) = 0` at every
  split `p`).
  SOURCE: Bannai–Kobayashi Cor. 3.12 [K. Bannai and S. Kobayashi, *Algebraic
  theta functions and the p-adic interpolation of Eisenstein–Kronecker
  numbers*, Duke Math. J. 153 (2010), no. 2, 229–295] + de Shalit II §4
  [op. cit.] for the local terms.
  PAPER: Lemma 3.5 (`lem:comparison`) (`L_p(E,T) = c_p · u(T) · L^{Katz}_𝔭(T)`).
  STATUS: classical (consequence-form: `c`, `u` taken as units). -/
  comparison : ∃ (c : Wˣ) (u : (PowerSeries W)ˣ),
      Lp.map (algebraMap ℤ_[p] W) = (c : W) • ((u : PowerSeries W) * LKatz)
  /-- The **grade-two core** `m2core ∈ W`: the `p^{-2}` lift of the grade-two
  moment sum, `M₂(𝔭) = p² · m2core` (Proposition 6.2(2) divisibility
  `v_p(M₂(𝔭)) ≥ 2`). Its residue mod 𝔭 is the criterion class `𝔠(𝔭)`
  (`criterionClass`).
  SOURCE: Proposition 6.2 (`prop:grading`)(2) (`M₂(𝔭) = p² · (𝔠(𝔭)-lift)`); de Shalit II §4 for
  the local moment terms.
  PAPER: Proposition 6.2 (`prop:grading`)(2). STATUS: data. -/
  m2core : W
  /-- **Grading congruence** (Proposition 6.1 + Proposition 6.2(1)): for a unit
  normalisation `κ₀ ∈ Wˣ` (absorbing `2 log_p(1+p)²`),
  `p² · (κ₀ · c₂(L^K) − m2core) ∈ (p³)`,
  i.e. `κ₀ · coeff 2 LKatz ≡ m2core (mod p)` after cancelling `p²` in the domain
  `W`. This is exactly the hypothesis of the abstract grading-valuation kernel
  (`isUnit_iff_residue_ne_zero_of_grading_congr`), which turns it into `IsUnit (coeff 2 LKatz) ↔ 𝔠(𝔭) ≠ 0`.

  **Honest descope.** Proposition 6.1 expresses `c₂(L^K) = ½∫m² dμ_ψ` as a
  second moment and Proposition 6.2(1) gives `2 log_p(1+p)² c₂(L^K) ≡ M₂(𝔭)
  (mod p³ W)`; the Eisenstein–Kronecker bookkeeping identifying `M₂(𝔭)`/`m2core`
  "to the last constant" is **not** carried in Lean. This
  field records only the resulting algebraic congruence between `coeff 2 LKatz`
  and `m2core`.
  SOURCE: Bannai–Kobayashi Prop. 3.3 / Thm. 3.7 [Duke Math. J. 153 (2010),
  229–295] (moment ↔ Eisenstein–Kronecker display) + de Shalit II §4.
  PAPER: Proposition 6.1 (`prop:jetformula`), Proposition 6.2 (`prop:grading`)(1).
  STATUS: consequence-form. -/
  grading_congr : ∃ κ₀ : Wˣ,
      (p : W) ^ 2 * ((κ₀ : W) * coeff 2 LKatz - m2core) ∈ Ideal.span {(p : W) ^ 3}

attribute [instance] KatzData.commRing KatzData.isDomain KatzData.isLocalRing
  KatzData.algebra

namespace KatzData

variable {p : ℕ} [Fact p.Prime] {Lp : Λ p}

/-- The **criterion class** `𝔠(𝔭) = p^{-2} M₂(𝔭) mod 𝔭 ∈ residue field of W`
of Proposition 6.2, as the residue of `m2core`.

This is a **def, not a field**: it is the object the grading-valuation kernel
`isUnit_iff_residue_ne_zero_of_grading_congr` links to `IsUnit (coeff 2 LKatz)`.
PAPER: Proposition 6.2 (`prop:grading`) (the criterion class `𝔠(𝔭)`). -/
noncomputable def criterionClass (K : KatzData p Lp) : IsLocalRing.ResidueField K.W :=
  IsLocalRing.residue K.W K.m2core

/-- `algebraMap ℤ_[p] K.W` is a **local ring homomorphism**, derived from
`maxIdeal_eq_p`: a non-unit of `ℤ_[p]` lies in `(p) = maximalIdeal ℤ_[p]`, so
its image lies in `(p) = maximalIdeal K.W`, hence is a non-unit.

Provided so that the unit-transfer step of Lemma 6.3 (`Kernel/Decoupling.lean`),
`IsUnit (coeff 2 (Lp.map (algebraMap ℤ_[p] W))) ↔ IsUnit (coeff 2 Lp)` via
`isUnit_map_iff`, has its `[IsLocalHom …]` instance ready without expanding
`KatzData`'s field list.
SOURCE: derived from `maxIdeal_eq_p` + `PadicInt.maximalIdeal_eq_span_p`. -/
theorem algMap_isLocalHom (K : KatzData p Lp) : IsLocalHom (algebraMap ℤ_[p] K.W) := by
  refine ⟨fun {a} ha => ?_⟩
  by_contra hna
  have hmem : a ∈ IsLocalRing.maximalIdeal ℤ_[p] :=
    (IsLocalRing.mem_maximalIdeal a).mpr (mem_nonunits_iff.mpr hna)
  rw [PadicInt.maximalIdeal_eq_span_p, Ideal.mem_span_singleton] at hmem
  obtain ⟨b, rfl⟩ := hmem
  have hu : IsUnit ((p : K.W) * algebraMap ℤ_[p] K.W b) := by
    simpa [map_mul, map_natCast] using ha
  have hp : (p : K.W) ∈ IsLocalRing.maximalIdeal K.W := by
    rw [K.maxIdeal_eq_p, Ideal.mem_span_singleton]
  exact (mem_nonunits_iff.mp ((IsLocalRing.mem_maximalIdeal _).mp hp))
    (isUnit_of_mul_isUnit_left hu)

end KatzData

end FinShaRank2
